[build]
base = "."
publish = "client/dist"
command = "npm install && vite build"

[build.environment]
NODE_VERSION = "18"
VITE_API_BASE_URL = "https://stilclas.replit.app/api"

[[redirects]]
from = "/api/*"
to = "https://stilclas.replit.app/api/:splat"
status = 200
force = true

[[redirects]]
from = "/*"
to = "/index.html"
status = 200

[[headers]]
for = "/*"
[headers.values]
Content-Security-Policy = "frame-ancestors 'self' https://wesite.ro"
X-XSS-Protection = "1; mode=block"
X-Content-Type-Options = "nosniff"
Cache-Control = "public, max-age=31536000"

[[headers]]
for = "/index.html"
[headers.values]
Cache-Control = "public, max-age=0, must-revalidate"
